# Generated by Django 4.1.3 on 2022-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_carousel_options_carousel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.CharField(max_length=100, verbose_name='Адрес')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('enable', models.BooleanField(default=True, verbose_name='Включен')),
            ],
            options={
                'verbose_name': 'Навигация',
                'verbose_name_plural': 'Навигация',
                'ordering': ['pk'],
            },
        ),
    ]
