# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
    ]
