# Generated by Django 4.1.3 on 2022-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_navbar_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'ordering': ['order'], 'verbose_name': 'Навигация', 'verbose_name_plural': 'Навигация'},
        ),
        migrations.AddField(
            model_name='navbar',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
            preserve_default=False,
        ),
    ]
