# Generated by Django 4.1.3 on 2022-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='days_period1',
            field=models.CharField(blank=True, default='Понедельник - Пятница', max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='days_period2',
            field=models.CharField(blank=True, default='Суббота', max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='days_period3',
            field=models.CharField(blank=True, default='Воскресенье', max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='hours_period1',
            field=models.CharField(blank=True, default='10:00 - 18:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='footer',
            name='hours_period2',
            field=models.CharField(blank=True, default='10:00 - 14:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='footer',
            name='hours_period3',
            field=models.CharField(blank=True, default='Выходной', max_length=20),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twitter'),
        ),
    ]
