# Generated by Django 4.1.3 on 2022-11-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newsletters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletters',
            options={'ordering': ['created_at'], 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
