# Generated by Django 4.1.3 on 2022-11-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_newsletters_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Serving Since 1950', max_length=50)),
                ('headerImg', models.ImageField(upload_to='about_img/%Y/%m/%d/', verbose_name='Разделительное Фото')),
                ('contentStory', models.TextField(blank=True, verbose_name='Контент для Истории')),
                ('contentStoryEnable', models.BooleanField(default=True, verbose_name='Показывать Историю')),
                ('contentVision', models.TextField(blank=True, verbose_name='Контент для Видения')),
                ('contentVisionEnable', models.BooleanField(default=True, verbose_name='Показывать Видение')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
