# Generated by Django 4.1.3 on 2022-12-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['pk'], 'verbose_name': 'Мои контакты', 'verbose_name_plural': 'Мои контакты'},
        ),
        migrations.RemoveField(
            model_name='footer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='phone',
        ),
    ]
