# Generated by Django 4.1.3 on 2022-12-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название предложения')),
                ('sizeOFF', models.CharField(max_length=50, verbose_name='Размер скидки')),
                ('content', models.TextField(verbose_name='Описание')),
                ('enable', models.BooleanField(default=False, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ['-created_at'],
            },
        ),
    ]
