# Generated by Django 4.1.3 on 2022-12-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingInfo', models.CharField(max_length=100, verbose_name='Информация о бронировании')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.offer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Бронирование предложения',
                'verbose_name_plural': 'Брони предложения',
                'ordering': ['pk'],
            },
        ),
    ]
