# Generated by Django 4.1.3 on 2022-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_offerbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbooking',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='offerbooking',
            name='BookingInfo',
            field=models.CharField(max_length=200, verbose_name='Информация о бронировании'),
        ),
    ]
