# Generated by Django 4.1.3 on 2023-01-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_offerbooking_phone_alter_offerbooking_bookinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('short_name', models.CharField(default='', max_length=3, verbose_name='Коротко')),
                ('exchange_rate', models.FloatField(default=1.0, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип работы')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.FloatField(default=100.0, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='menu_img/%Y/%m/%d/', verbose_name='Фото работы')),
                ('info', models.TextField(blank=True, verbose_name='Описание')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.currency', verbose_name='Валюта')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.menutype', verbose_name='Тип работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['name'],
            },
        ),
    ]
