# Generated by Django 4.1.3 on 2023-01-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_currency_menutype_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон клиента')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email клиента')),
                ('date', models.DateField(verbose_name='Дата брони')),
                ('time', models.TimeField(verbose_name='Время брони')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('number_of_reservation', models.IntegerField(verbose_name='Номер брони')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Предварительная бронь',
                'verbose_name_plural': 'Предварительные брони',
                'ordering': ['created_at'],
            },
        ),
    ]
