# Generated by Django 4.1.3 on 2023-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
