# Generated by Django 4.1.3 on 2023-02-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_testimonial_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='page',
            field=models.CharField(blank=True, max_length=50, verbose_name='Страница'),
        ),
    ]
